---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: "Prepare Debian-based systems"
      when: ansible_facts.os_family == 'Debian'
      block:
        - name: "Update apt cache if necessary"
          ansible.builtin.apt:
            update_cache: true
            cache_valid_time: 300
